apiVersion: skaffold/v2beta27
kind: Config
build:
  artifacts:
    - image: my-super-web-app
      docker:
        dockerfile: frontend/Dockerfile
    # - image: spark-app
    #   docker:
    #     dockerfile: spark-app/Dockerfile
  local:
    useBuildkit: true
    push: false 
deploy:
  kubectl:
    manifests:
      - ./deployment/01-mariadb.yaml
      - ./deployment/02-memcached-deployment-and-service.yaml
      - ./deployment/03-app-deployment-skaffold.yaml
      - ./deployment/04-app-service-and-ingress.yaml
portForward:
- resourceType: service
  resourceName: my-super-app-service
  port: 8080
  localPort: 8080
- resourceType: service
  resourceName: my-app-mariadb-service
  port: 3306
  localPort: 3306